# Generated by Django 3.1.1 on 2020-11-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='estado',
            field=models.CharField(max_length=20),
        ),
    ]
